# Generated by Django 4.2.1 on 2023-05-16 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profesor',
            name='contraseña',
        ),
        migrations.RemoveField(
            model_name='profesor',
            name='nombre_usuario',
        ),
    ]
