# Generated by Django 4.1.7 on 2023-05-17 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_profesor_contraseña_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('email', models.CharField(max_length=50, verbose_name='email')),
                ('password1', models.CharField(max_length=50, verbose_name='password1')),
                ('password2', models.CharField(max_length=50, verbose_name='password2')),
            ],
        ),
    ]
